=== Timo1979-x/ais-fileimporter/src/main/resources/files/xchange_v3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by TeaM DJiNN (TeaM DJiNN) -->
<!--W3C Schema generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="emptyString">
        <xs:restriction base="xs:string">
            <xs:maxLength value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="decimalOrEmpty">
        <xs:union memberTypes="xs:decimal emptyString"/>
    </xs:simpleType>
    <xs:simpleType name="intOrEmpty">
        <xs:union memberTypes="xs:integer emptyString"/>
    </xs:simpleType>
    <xs:simpleType name="longOrEmpty">
        <xs:union memberTypes="xs:long emptyString"/>
    </xs:simpleType>
    <xs:simpleType name="code9">
        <xs:annotation>
            <xs:documentation xml:lang="ru">
                9-значный код станции
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:unsignedInt">
            <xs:minInclusive value="100000000"/>
            <xs:maxInclusive value="999999999"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="GUID">
        <xs:annotation>
            <xs:documentation xml:lang="ru">
                The representation of a GUID, generally the id of an element.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="msg">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hdr"/>
                <xs:element name="Info" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="PTI" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="hdr">
        <xs:complexType>
            <xs:attribute name="ver" type="xs:unsignedInt" use="required"/>
            <xs:attribute name="to" type="GUID" use="required"/>
            <xs:attribute name="from" type="GUID" use="required"/>
            <xs:attribute name="received" type="xs:unsignedInt" use="required"/>
            <xs:attribute name="msg_number" type="xs:unsignedInt" use="required"/>
            <xs:attribute name="date" type="xs:dateTime" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="PTI">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="deletions"/>
                <xs:element ref="changes"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="deletions">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="del" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="del">
        <xs:complexType>
            <xs:attribute name="guid" type="GUID" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="changes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Doc" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Doc">
        <xs:complexType>
            <xs:attribute name="id_dso_diagn_card" type="xs:unsignedInt" use="optional"/>
            <xs:attribute name="guid" type="GUID" use="required"/>
            <xs:attribute name="ds_code" type="code9" use="required"/>
            <xs:attribute name="dc_seria" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value=".{2,3}"/>
                        <!--<xs:pattern value="[a-zA-ZА-Яа-я]{2,3}"/> -->
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="dc_number" type="xs:unsignedInt" use="required"/>
            <xs:attribute name="dateto" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d\d\.\d\d\.\d{4} \d?\d:\d\d:\d\d"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="method_izm" type="xs:unsignedInt" use="optional"/>
            <xs:attribute name="reg_number" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="4"/>
                        <xs:maxLength value="15"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="dateauto" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:unsignedShort">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="2200"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="tc_seria" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="15"/>
                        <!--<xs:pattern value="[a-zA-ZА-Яа-я \d]{0,4}"/>-->
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="tc_number" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="11"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="vin_is_chassi" type="xs:unsignedByte" use="required"/>
            <xs:attribute name="vin" type="xs:string" use="optional"/>
            <xs:attribute name="id_ts_type" type="xs:unsignedByte" use="required"/>
            <xs:attribute name="id_ts_type_engine" type="xs:unsignedByte" use="required"/>
            <xs:attribute name="model_id" type="xs:unsignedInt" use="required"/>
            <xs:attribute name="id_ts_categ" type="xs:unsignedByte" use="required"/>
            <xs:attribute name="id_ts_use" type="xs:unsignedByte" use="required"/>
            <xs:attribute name="id_ts_colour" type="xs:unsignedShort" use="required"/>
            <xs:attribute name="eko_class" type="xs:string" use="optional"/>
            <xs:attribute name="weight" type="xs:unsignedInt" use="required"/>
            <xs:attribute name="mileage" type="longOrEmpty" use="required"/>
            <xs:attribute name="parent" type="xs:string" use="optional"/>
            <xs:attribute name="dl_seria" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="20"/>
                        <!--<xs:pattern value="[a-z A-ZА-Яа-я\d]{1,5}"/>-->
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="dl_number" type="xs:unsignedLong" use="optional"/>
            <xs:attribute name="num_inspection" type="xs:unsignedInt" use="optional"/>
            <xs:attribute name="check" type="xs:string" use="optional"/>
            <xs:attribute name="notes" type="xs:string" use="optional"/>
            <xs:attribute name="mismatch" type="xs:string" use="optional"/>
            <xs:attribute name="photo" type="xs:unsignedInt" use="optional"/>
            <xs:attribute name="conclusion" type="xs:unsignedByte" use="optional"/>
            <xs:attribute name="owner_name" type="xs:string" use="optional"/>
            <xs:attribute name="owner_type" type="xs:unsignedByte" use="optional"/>
            <xs:attribute name="owner_unp" type="xs:string" use="optional"/>
            <xs:attribute name="customer_name" type="xs:string" use="optional"/>
            <xs:attribute name="customer_type" type="xs:string" use="optional"/>
            <xs:attribute name="customer_unp" type="xs:string" use="optional"/>
            <xs:attribute name="symma_s_nds" type="xs:decimal" use="optional"/>
            <xs:attribute name="symma_nds" type="decimalOrEmpty" use="optional"/>
            <xs:attribute name="blanc_repeat_date" type="xs:string" use="optional"/>
            <xs:attribute name="blanc_repeat_seria" type="xs:string" use="optional"/>
            <xs:attribute name="blanc_repeat_number" type="xs:string" use="optional"/>
            <xs:attribute name="user_name" type="xs:string" use="optional"/>
            <!-- <xs:attribute name="dc_seria" type="xs:string" use="required"/> -->
            <!--<xs:attribute name="tc_number" type="xs:unsignedInt" use="required"/>-->
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Timo1979-x/ais-fileimporter/src/main/resources/files/xchange_v3.xml
<?xml version="1.0" encoding="utf-8"?>
<msg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xchange_v3.xsd">
    <hdr ver="3" from="a5b865ac-a075-4055-bbb8-0dd97348bf67" to="543e004d-8754-4d1d-97a9-f84d9f3bb00d"
         date="2019-11-15T13:23:58" msg_number="12" received="45"/>
    <!--Ошибочно введенная станция-->
    <Info Version_App="3.1.5.0" Version_App_DB="204" Version_DB="204"/>
    <PTI>
        <deletions>
            <del guid="d3938723-f808-41f2-a5e3-6abe31b6c4e7"/>
            <del guid="9a1d1eba-e516-427b-9961-6af23cd61d66"/>
        </deletions>
        <changes>
            <Doc guid="357dafeb-7e19-4bef-8c66-c434ff0e64aa" id_dso_diagn_card="96710" ds_code="999999998" dc_seria="БЧ"
                 dc_number="487163" dateto="15.11.2019 13:21:45" method_izm="1" reg_number="5855IT-7" dateauto="2001"
                 tc_seria="МАА" tc_number="730646" vin_is_chassi="0" vin="VF7CHRHYB39060042" id_ts_type="9"
                 id_ts_type_engine="4" model_id="7003090" id_ts_categ="1" id_ts_use="1" id_ts_colour="538" eko_class="1"
                 weight="1835" mileage="3" parent="ЧЕРЕПОВСКИЙ ПАВЕЛ АЛЕКСАНДРОВИЧ" dl_seria="7АВ" dl_number="136724"
                 num_inspection="0"
                 check="101,104,105,201,202,203,204,301,302,303,304,305,401,402,403,404,405,501,502,503,504,602,605,606,701,702,703,801,802,803,901,902,904,905,906,908,909,910,1001,1002,1003,1004,1101,1102"
                 notes="" mismatch="1,5,7" photo="0" conclusion="2" owner_name="КУВШИННИКОВ АЛЕКСАНДР БОРИСОВИЧ"
                 owner_type="1" owner_unp="" customer_name="" customer_type="" customer_unp="" symma_s_nds="1.00"
                 symma_nds="0.00" blanc_repeat_date="" blanc_repeat_seria="" blanc_repeat_number=""
                 user_name="САВЕЛЬЕВ ПАВЕЛ  АЛЕКСАНДРОВИЧ"/>
        </changes>
    </PTI>
</msg>
